import type { AuthError } from '../../errors.js'
import type { SupabaseContext, WithSupabaseConfig } from '../../types.js'
import { withSupabase as baseWithSupabase } from '../../with-supabase.js'

/**
 * Spec for {@link defineAdapter}.
 *
 * @template NativeContext - The framework's native route-handler input
 *   (e.g. Hono's `Context`, H3's `H3Event`, Elysia's route args). The
 *   produced two-arg `withSupabase` accepts `Request | NativeContext`
 *   and extracts the underlying Request via {@link extractRequest}.
 * @template MiddlewareReturn - What the adapter's one-arg
 *   `withSupabase(config)` returns — typically the framework's native
 *   middleware or plugin type. Inferred from {@link middleware}.
 */
export interface AdapterSpec<NativeContext, MiddlewareReturn> {
  /** Adapter name, surfaced in error messages (e.g. `'hono'`). */
  name: string

  /**
   * Returns the underlying `Request` carried by the framework's native
   * route input. Should return `undefined` when the input isn't
   * recognized as a `NativeContext` — `defineAdapter` will then throw
   * a `TypeError` naming the adapter.
   */
  extractRequest: (input: NativeContext) => Request | undefined

  /**
   * Returns an existing {@link SupabaseContext} already attached to the
   * framework's native input by an upstream middleware/plugin (e.g.
   * `c.var.supabaseContext` for Hono). When this returns a value, the
   * two-arg form skips base auth and invokes the inner handler
   * directly with the existing context — matching the
   * skip-if-already-set behavior of the one-arg middleware form.
   *
   * Omit to disable skip behavior (every two-arg call runs base auth).
   */
  getExistingContext?: (input: NativeContext) => SupabaseContext | undefined

  /**
   * Maps an `AuthError` from base auth into a framework-native error
   * thrown into the framework's error pipeline (e.g. Hono's
   * `HTTPException` → `onError`). Must throw — return type is `never`
   * and any returned value is ignored.
   *
   * When provided, passed as `onAuthError` to base on every two-arg
   * call. Omit to fall back to base's default JSON error response.
   */
  throwAuthError?: (error: AuthError) => never

  /**
   * Builds the framework-native middleware/plugin that the one-arg
   * `withSupabase(config)` returns. The return type is captured by
   * {@link MiddlewareReturn} and flows through to the adapter's
   * exported `withSupabase` so consumers see the right native type.
   *
   * This is the only bespoke part of the adapter — its body uses the
   * framework's own primitives (`createMiddleware`, `defineMiddleware`,
   * `new Elysia().resolve(...)`, etc.) and is genuinely
   * framework-specific. The two-arg dual-mode form is generated by
   * `defineAdapter` and identical across adapters.
   */
  middleware: (config?: Omit<WithSupabaseConfig, 'cors'>) => MiddlewareReturn
}

/**
 * The fully overloaded `withSupabase` function each adapter exports.
 *
 * - **One arg** — `withSupabase(config)` returns the framework-native
 *   middleware/plugin built by {@link AdapterSpec.middleware}.
 * - **Two args** — `withSupabase(config, handler)` returns a dual-mode
 *   route handler that accepts either a `Request` (Web Fetch use) or
 *   the framework's `NativeContext` (mounted on a route), extracts the
 *   underlying Request, and runs base `withSupabase` against it.
 */
export interface AdapterWithSupabase<NativeContext, MiddlewareReturn> {
  (config?: Omit<WithSupabaseConfig, 'cors'>): MiddlewareReturn
  (
    config: Omit<WithSupabaseConfig, 'cors' | 'onAuthError'>,
    handler: (req: Request, ctx: SupabaseContext) => Promise<Response>,
  ): (input: Request | NativeContext) => Promise<Response>
  <Database>(
    config: Omit<WithSupabaseConfig, 'cors' | 'onAuthError'>,
    handler: (
      req: Request,
      ctx: SupabaseContext<Database>,
    ) => Promise<Response>,
  ): (input: Request | NativeContext) => Promise<Response>
}

/**
 * Build a framework adapter's `withSupabase` export.
 *
 * Returns a single fully-overloaded `withSupabase` function. The
 * one-arg form dispatches to the spec's `middleware` factory (the
 * framework-native middleware/plugin). The two-arg form is generated
 * by `defineAdapter` — a dual-mode route handler that accepts either
 * `Request` or the framework's native input, extracts the underlying
 * Request, and runs base `withSupabase` against it.
 *
 * The two-arg form is uniform across adapters (only the
 * extraction function varies); the one-arg form is each framework's
 * own idiom (middleware function for Hono/H3, plugin object for
 * Elysia, etc.). `defineAdapter` centralizes the former and lets each
 * adapter own the latter via the {@link AdapterSpec.middleware} field.
 *
 * On the two-arg form:
 * - **CORS is forced off** (`cors: false`). CORS belongs to the
 *   framework's CORS middleware, not the adapter.
 * - **`getExistingContext`** (optional) lets the two-arg form skip
 *   base auth when an upstream middleware already populated
 *   `supabaseContext`, matching one-arg skip-if-set behavior.
 * - **`throwAuthError`** (optional) maps auth failures to a
 *   framework-native error thrown into the framework's error
 *   pipeline, matching one-arg error semantics.
 *
 * @example Hono
 * ```ts
 * import type { Context, MiddlewareHandler } from 'hono'
 * import { HTTPException } from 'hono/http-exception'
 * import { createMiddleware } from 'hono/factory'
 * import { defineAdapter } from '@supabase/server/core/adapters'
 *
 * export const { withSupabase } = defineAdapter<
 *   Context,
 *   MiddlewareHandler<{ Variables: { supabaseContext: SupabaseContext } }>
 * >({
 *   name: 'hono',
 *   extractRequest: (c) => c.req.raw,
 *   getExistingContext: (c) => c.var.supabaseContext,
 *   throwAuthError: (error) => {
 *     throw new HTTPException(error.status as 401 | 500, {
 *       message: error.message,
 *       cause: error,
 *     })
 *   },
 *   middleware: (config) =>
 *     createMiddleware<{ Variables: { supabaseContext: SupabaseContext } }>(
 *       async (c, next) => {
 *         // framework-specific body (skip-if-set, throw HTTPException, etc.)
 *       },
 *     ),
 * })
 * ```
 */
export function defineAdapter<NativeContext, MiddlewareReturn>(
  spec: AdapterSpec<NativeContext, MiddlewareReturn>,
): { withSupabase: AdapterWithSupabase<NativeContext, MiddlewareReturn> } {
  function extract(input: Request | NativeContext): Request {
    if (input instanceof Request) return input
    const req = spec.extractRequest(input)
    if (!(req instanceof Request)) {
      throw new TypeError(buildErrorMessage(spec.name, input))
    }
    return req
  }

  function twoArg<Database = unknown>(
    config: Omit<WithSupabaseConfig, 'cors' | 'onAuthError'>,
    handler: (
      req: Request,
      ctx: SupabaseContext<Database>,
    ) => Promise<Response>,
  ): (input: Request | NativeContext) => Promise<Response> {
    const baseConfig: WithSupabaseConfig = {
      ...config,
      cors: false,
      ...(spec.throwAuthError ? { onAuthError: spec.throwAuthError } : {}),
    }
    const inner = baseWithSupabase<Database>(baseConfig, handler)

    return (input) => {
      if (input instanceof Request) return inner(input)
      const req = extract(input)
      const existing = spec.getExistingContext?.(input)
      if (existing) return handler(req, existing as SupabaseContext<Database>)
      return inner(req)
    }
  }

  function withSupabase(
    config?: WithSupabaseConfig,
    handler?: (req: Request, ctx: SupabaseContext) => Promise<Response>,
  ):
    | MiddlewareReturn
    | ((input: Request | NativeContext) => Promise<Response>) {
    if (handler) return twoArg(config!, handler)
    return spec.middleware(config)
  }

  return {
    withSupabase: withSupabase as AdapterWithSupabase<
      NativeContext,
      MiddlewareReturn
    >,
  }
}

function buildErrorMessage(name: string, received: unknown): string {
  const what =
    received === null || typeof received !== 'object'
      ? typeof received
      : ((received as { constructor?: { name?: string } }).constructor?.name ??
        'object')
  return (
    `withSupabase from @supabase/server/adapters/${name} expected a Request or a ${name} route context, ` +
    `but received ${what}. Mount via \`app.all(path, withSupabase(config, handler))\` (or the equivalent for your framework).`
  )
}
